spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025 # port of our application
    username: lamine
    password: ooo #not required
    properties:
       mail:
         smtp:
           trust: "*"
         auth: true
         starttls:
           enable: true # secure connection in the context of sending mails
         connectiontimeout: 5000
         timeout: 3000
         writetimeout: 5000


application:
  security:
    jwt:
      secret-key: EC9qxeu73j8pXl/reiWyXTWc/5xg7GRbCk6Mjsxh12I=
      expiration : 8640000
